### ISSUE TITLE
Update to Laravel 4.2

### ISSUE THREAD

**Issue by juanjolainez** [Radweb/JSON-Exception-Formatter#2]
Hi! 

While making a composer update to upgrade to Laravel 4.2 I receive this error:

radweb/json-exception-formatter dev-master requires illuminate/http 4.1.\*  ....

I can not upgrade for this dependency and I think illuminate/http is some laravel dependency as well, right? 
Shouldn't it be enough to remove it to solve the issue? 

Thank you!

**Comment by danharper** [comment]
I've lowered the required dependency from 4.1.\* to just 4.\* which should do the job :).
